### ISSUE TITLE
Add more-detailed meta information for CSRs.

### ISSUE THREAD

**Issue by bgs100** [rv8-io/rv8#42]
Currently, `meta/csrs` contains basic information about CSRs such as numbers, permissions, and names. `meta/enums` also lists some of the specific fields of CSRs, such as the possible values and meanings of, for example, `mstatus.fs`. However, information about the structure of CSRs, such as the location of fields (e.g. which bits of `mstatus` correspond to `fs`?) is non-existent in `meta/`. Currently, this information exists in `emu/processor-priv-1.9.h` for a few machine-level CSRs.

It would be useful to have this information (along with information about whether a field is WIRI, WPRI, WLRL, or WARL) encoded in plain text in `meta/`, possibly in the style of `meta/operands`.

**Comment by michaeljclark** [comment]
That would be useful. Only a relatively small number of CSRs have fields. Perhaps a `csr-fields` file with flattened structures. It is important to capture version information as the intention is to support multiple versions of the privileged spec e.g. `emu/processor-priv-1.9.h` and `emu/processor-priv-1.10.h`. The first section of these files that defines the bitfield structures for the CSRs could then be autogenerated.

Perhaps something like this:

```
mstatus    uie  0     1.9-    "User mode Interrupt Enable"
mstatus    sie  1     1.9-    "Supervisor mode Interrupt Enable"
mstatus    hie  2     1.9-    "Hypervisor mode Interrupt Enable"
mstatus    mie  3     1.9-    "Machine mode Interrupt Enable"
mstatus    upie 4     1.9-    "Prior User mode Interrupt Enable"
mstatus    spie 5     1.9-    "Prior Supervisor mode Interrupt Enable"
mstatus    hpie 6     1.9-    "Prior Hypervisor mode Interrupt Enable"
mstatus    mpie 7     1.9-    "Prior Machine mode Interrupt Enable"
#mstatus   upp        1.9-    "URET pop privilege (implicitly 0)"
mstatus    spp  8     1.9-    "SRET pop privilege"
mstatus    hpp  10:9  1.9-    "HRET pop privilege"
mstatus    mpp  12:11 1.9-    "MRET pop privilege"
mstatus    fs   14:13 1.9-    "FPU register status"
mstatus    xs   16:15 1.9-    "Extension status"
mstatus    mprv 17    1.9-    "Data access at 'mpp' privilege level when enabled"
mstatus    pum  18    1.9-    "Protect User Memory causes U mode accesses to fault when enabled"
mstatus    mxr  19    1.9-    "Make eXecute Readable allows loads from X-only pages when enabled"
mstatus    wpri 23:20 1.9-    "Reserved"
```

**Comment by michaeljclark** [comment]
I've added a csr-fields file to the meta directory:

https://github.com/rv8-io/rv8/blob/master/meta/csr-fields

There should be enough information to construct masks and shift constants or bitfield structures.
